
include:
  - board: nice_nano//zmk
    shield: ekeeb
#  - board: nice_nano//zmk
#    shield: settings_reset
#  - board: bluemicro840_v1
#    shield: ekeeb
#  - board: bluemicro840_v1
#    shield: settings_reset


